[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center", "--transition-step", "15", "--transition-fps", "60"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
